version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    groups:
      mermaid:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /
    target-branch: main
    schedule:
      interval: monthly
